### PR TITLE
account manager fixes

### PR DESCRIPTION
**Pull request by R15User**

### CODE REVIEW

**Comment by SkySwimmer** [comment]
R15 you are hereby blacklisted from server development for removing security checks

**Comment by Cpeers1** [comment]
To clarify: You didn't remove 'security' checks persay, just removed checks relating to usernames, file names, length and name validity checks. It's not a security BREACH, but it is a downgrade from our current level of security.

**Comment by R15User** [comment]
no security checks were removed at all. the blocked list was redundant when you have a blocked list being read from file?

**Comment by SkySwimmer** [comment]
my github decided to break when i reviewed and it only showed removals-

**Comment by R15User** [comment]
could my pull request be reopened and committed?

**Comment by R15User** [comment]
> my github decided to break when i reviewed and it only showed removals- sorry about the panic

in your fairness, i should've put a description of the changes i made.

**Pull request closed without merging**
