### PR TITLE
Beta 1.5.2

### PR DESCRIPTION
**Pull request by SkySwimmer**
Mostly security stuff

### CODE REVIEW

**Comment by SkySwimmer** [comment]
GAH WHY DID IT INCLUDE THE LIBRARIES AGAIN ITS ON THE GITIGNORE

**Comment by SkySwimmer** [comment]
Oh yeah discord4j update

**Comment by SkySwimmer** [comment]
Nvm then

**Review by Cpeers1 — APPROVED** [review]
My god this PR is absolutely massive. I'm not going to review it all but I assume you know what you are doing. In the future, lets aim for smaller more frequent PRs.

**Pull request merged**
